### ISSUE TITLE
maxFeeTokenId assert

### ISSUE THREAD

**Issue by glitchyg** [Montspy/LoopMintPy#22]
In minter.py there is an assert:
`assert cfg.maxFeeTokenId, "Missing fee token ID (FEE_TOKEN_ID)"`

The issue is if you have your token type set to ETH (value 0) this assert will fire off

**Comment by Montspy** [comment]
Thanks for filing this issue. Fixed in 366f6d4b41f7dd1cc59be9c781dd7f8bc8992957
