### ISSUE TITLE
paths.mint_info parent folder

### ISSUE THREAD

**Issue by glitchyg** [Montspy/LoopMintPy#23]
Inside minter.py there is the following code:

```
if not os.path.exists(paths.mint_info):
        os.makedirs(paths.mint_info)
```

In my case `paths.mint_info` is `./mint-info.json`

What happens is then that folder is created with the name "mint-info.json". When the script goes to dump the results, I get a is Directory error. I fixed this with the following code:

```
from pathlib import Path
parentFolder = Path(paths.mint_info).parent
if not os.path.exists(parentFolder):
        os.makedirs(parentFolder)
```

**Comment by Montspy** [comment]
Thanks for filing this issue. Fixed in 366f6d4b41f7dd1cc59be9c781dd7f8bc8992957
