### ISSUE TITLE
Not getting full balance of NFTs

### ISSUE THREAD

**Issue by glitchyg** [Montspy/LoopMintPy#26]
I currently have around 1007 NFTs in my account. I had the issue of the NFT I am trying to send not being found. I tracked it down to the line below. It seems 500 might be too many to request. I dropped this to 50 and then everything worked fine. 

https://github.com/Montspy/LooPyMinty/blob/a895ac9675bdda63d2fc68d774d56c2f48585105/LoopringMintService.py#L199

**Comment by Montspy** [comment]
Thanks!
Fixed in 490fc3e1d75ade8a483724c90c3f5bae6dbaf864
