### ISSUE TITLE
Make sure to lower-case all hex-strings

### ISSUE THREAD

**Issue by Montspy** [Montspy/LoopMintPy#27]
This NFT has been minted with mixed-case hex-strings and the explorer only likes lowercase hex-strings
![image](https://user-images.githubusercontent.com/2715455/165160350-d7075f94-c42c-4a30-a3d2-59fbd0009022.png)
Lowercase link works: https://explorer.loopring.io/nft/0xb55e31fadf5ab9d0b96abd084bb37c66d51c47cf-0-0x13dfecf3f60c597b5dd1264efb9951020db3462f-0x66e51aeb752c24f9608747e824f9f8fc9fcf42fb5ab96a6f293ced97093112c3-5
Mixed case like doesn't work (from loopring.io > My NFT UI): https://explorer.loopring.io/nft/0xB55E31FadF5Ab9d0B96ABD084bB37C66d51c47CF-0-0x13dFECF3F60C597b5dd1264EFb9951020Db3462f-0x66e51aeb752c24f9608747e824f9f8fc9fcf42fb5ab96a6f293ced97093112c3-5

**Comment by glitchyg** [comment]
To add to this, ens domains will not resolve if it is not lowercase

**Comment by Montspy** [comment]
Also important to do that for “to” addresses for the transfer tool

**Comment by Montspy** [comment]
Applied to minter in PR #29 
Applied to transfer tool in commit 02bfbb8f9d7433d4eccdc5bc823bd0dd4334eea9

**Comment by Montspy** [comment]
Merged #29 
Closing as fixed
